import { Hero } from './hero';

export const HEROES: Hero[] = [
  {id:1 ,avatar:"https://img.etimg.com/thumb/msid-50230136,width-300,height-225,imgsize-197883,,resizemode-75/.jpg",name:'APJ Abdul Kalam' ,field:'Scientist',info:'Avul Pakir Jainulabdeen Abdul Kalam BR was an Indian aerospace scientist and statesman who served as the 11th president of India from 2002 to 2007. He was born and raised in Rameswaram, Tamil Nadu and studied physics and aerospace engineering.'},
  {id:2 ,avatar:"https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcThaNfoY2Y11UfcYszjJglXbiAX91b6wrbJStP6fXHLJmdEQcDWfxnwk9fGwnLhGvn9e1oHAbzCHliNGt0",name:'Ratan Tata' ,field:'Industry',info:'Ratan Naval Tata is an Indian industrialist, philanthropist and former chairman of Tata Sons. He was a chairman of the Tata Group from 1990 to 2012, and interim chairman from October 2016 through February 2017. He continues to head its charitable trusts.'},
  {id:3 ,avatar:"https://akm-img-a-in.tosshub.com/indiatoday/images/story/202302/the_monk_ahead_of_his_times_1-sixteen_nine.jpg?VersionId=..8halMNnnGR1cdMwltNP_igxtvEP4rN&size=690:388",name:'Swami Vivekananda' ,field:'Philosopher',info:'Swami Vivekananda, born Narendranath Datta, was an Indian Hindu monk, philosopher, author, religious teacher, and the chief disciple of the Indian mystic Ramakrishna.'},
  {id:4 ,avatar:"https://static.toiimg.com/thumb/msid-96131622,imgsize-49438,width-400,resizemode-4/96131622.jpg",name:'Virat Kohli' ,field:'Sportsmen',info:'Virat Kohli is an Indian international cricketer and the former captain of the Indian national cricket team. Widely regarded as one of the greatest batsmen in the history of the sport, he plays for Royal Challengers Bangalore in the IPL and Delhi in domestic cricket'},
  {id:5 ,avatar:"https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSpNWC8pbqyPBG_GSAGQTgCPKJDgKKHwODg34nbnIL6U5xykRk4wvNAxCHUx5h_gWgDdIwo1nKykp3kOfI",name:'Messi' ,field:'Sportsmen',info:'Lionel Andrés Messi, also known as Leo Messi, is an Argentine professional footballer who plays as a forward for and captains both Major League Soccer club Inter Miami and the Argentina national team.'},        
];
